version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestFlowsProject
  gitServerName: testGitFeaturesP
  gitUrl: https://github.com/PoojaAnandGit/TestFlowsProject
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: EdgePkg1
  version: "1.0"
  gitServerName: testInternal
  gitUrl: https://github.webmethods.io/hasv
  gitUsername: poan
  gitBranch: master
services:
- serviceName: project.testflows.integrations:edgeflows
  packages:
  - name: TestFlowsProject
    version: "1.0"
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: project.testflows.integrations:testtree
  packages:
  - name: TestFlowsProject
    version: "1.0"
  - name: EdgePkg1
    version: "1.0"
- serviceName: pub.date:getCurrentDateString
  packages:
  - name: WmPublic
    version: 11.0.0.0.927
