version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestFlowsProject
  gitServerName: testGitFeaturesP
  gitUrl: https://github.com/PoojaAnandGit/TestFlowsProject
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testflows.integrations:edgeflows
  packages:
  - name: TestFlowsProject
    version: "1.0"
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
